Blink_server/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
  }
  resources :histories
  resources :cloths
 
  root to: 'users/dashboards#home' 
  namespace :users do
    resources :dashboards, only:[] do
      collection do
        get 'home'
        post 'fetch'
      end
    end
  end

end

Blink_server/app/models/cloth.rb
class Cloth < ActiveRecord::Base
  belongs_to :user
  has_many :histories, through: :cloths_histories
  mount_uploader :cloth_image, ClothImageUploader
end

Blink_server/app/controllers/cloths_controller.rb
class ClothsController < ApplicationController
  before_action :set_cloth, only: [:show, :edit, :update, :destroy]

  # GET /cloths
  # GET /cloths.json
  def index
    @cloths = Cloth.all
  end

  # GET /cloths/1
  # GET /cloths/1.json
  def show
  end

  # GET /cloths/new
  def new
    @cloth = Cloth.new
  end

  # GET /cloths/1/edit
  def edit
  end

  # POST /cloths
  # POST /cloths.json
  def create
    @cloth = Cloth.new(cloth_params)
    @cloth.user_id = current_user.id
    respond_to do |format|
      if @cloth.save
        format.html { redirect_to root_path }
        format.json { render :show, status: :created, location: @cloth }
      else
        format.html { render :new }
        format.json { render json: @cloth.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cloths/1
  # PATCH/PUT /cloths/1.json
  def update
    respond_to do |format|
      if @cloth.update(cloth_params)
        format.html { redirect_to @cloth, notice: 'Cloth was successfully updated.' }
        format.json { render :show, status: :ok, location: @cloth }
      else
        format.html { render :edit }
        format.json { render json: @cloth.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cloths/1
  # DELETE /cloths/1.json
  def destroy
    @cloth.destroy
    respond_to do |format|
      format.html { redirect_to cloths_url, notice: 'Cloth was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cloth
      @cloth = Cloth.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cloth_params
      params.require(:cloth).permit(:name, :beacon_identification_key, :user_id, :url, :cloth_image)
    end
end

Blink_server/app/helpers/cloths_helper.rb
module ClothsHelper
end

Blink_server/app/views/cloths/_form.html.erb
<%= form_for(@cloth) do |f| %>
  <% if @cloth.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cloth.errors.count, "error") %> prohibited this cloth from being saved:</h2>

      <ul>
      <% @cloth.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :beacon_identification_key %><br>
    <%= f.text_field :beacon_identification_key %>
  </div>
  <div class="field">
    <%= f.label :cloth_image %>
    <%= f.file_field :cloth_image %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Blink_server/app/views/cloths/edit.html.erb
<h1>Editing Cloth</h1>

<%= render 'form' %>

<%= link_to 'Show', @cloth %> |
<%= link_to 'Back', cloths_path %>

Blink_server/app/views/cloths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cloths</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Beacon identification key</th>
      <th>User</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cloths.each do |cloth| %>
      <tr>
        <td><%= cloth.name %></td>
        <td><%= cloth.beacon_identification_key %></td>
        <td><%= cloth.user %></td>
        <td><%= cloth.url %></td>
        <td><%= link_to 'Show', cloth %></td>
        <td><%= link_to 'Edit', edit_cloth_path(cloth) %></td>
        <td><%= link_to 'Destroy', cloth, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cloth', new_cloth_path %>

Blink_server/app/views/cloths/new.html.erb
<h1>New Cloth</h1>

<%= render 'form' %>

<%= link_to 'Back', cloths_path %>

Blink_server/app/views/cloths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cloth.name %>
</p>

<p>
  <strong>Beacon identification key:</strong>
  <%= @cloth.beacon_identification_key %>
</p>

<p>
  <strong>User:</strong>
  <%= @cloth.user %>
</p>

<p>
  <strong>Url:</strong>
  <%= @cloth.url %>
</p>

<%= link_to 'Edit', edit_cloth_path(@cloth) %> |
<%= link_to 'Back', cloths_path %>