Blink_server/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
  }
  resources :histories
  resources :cloths
 
  root to: 'users/dashboards#home' 
  namespace :users do
    resources :dashboards, only:[] do
      collection do
        get 'home'
        post 'fetch'
      end
    end
  end

end

Blink_server/app/models/history.rb
class History < ActiveRecord::Base
  belongs_to :user
  has_many :cloths, through: :cloths_histories
  has_many :cloths_histories
  accepts_nested_attributes_for :cloths_histories
end

Blink_server/app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: [:show, :edit, :update, :destroy]

  # GET /histories
  # GET /histories.json
  def index
    @histories = History.all
  end

  # GET /histories/1
  # GET /histories/1.json
  def show
  end

  # GET /histories/new
  def new
    @history = History.new
    @history.cloths_histories.build
    @cloths = current_user.cloths
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories
  # POST /histories.json
  def create
    @history = History.new(history_params)
    @history.user_id = current_user.id

    respond_to do |format|
      if @history.save
        format.html { redirect_to @history, notice: 'History was successfully created.' }
        format.json { render :show, status: :created, location: @history }
      else
        format.html { render :new }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histories/1
  # PATCH/PUT /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to @history, notice: 'History was successfully updated.' }
        format.json { render :show, status: :ok, location: @history }
      else
        format.html { render :edit }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history.destroy
    respond_to do |format|
      format.html { redirect_to histories_url, notice: 'History was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def history_params
      params.require(:history).permit(:location, :user_id, cloths_histories_attributes: [:cloth_id])
    end
end

Blink_server/app/helpers/histories_helper.rb
module HistoriesHelper
end

Blink_server/app/views/histories/_cloths_fields.html.erb
<fieldset>
  <%= f.label :cloth_id, 'name' %>
  <%= f.collection_select(:cloth_id, @cloths, :id, :name) %>
</fieldset>

Blink_server/app/views/histories/_form.html.erb
<%= form_for(@history) do |f| %>
  <% if @history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@history.errors.count, "error") %> prohibited this history from being saved:</h2>

      <ul>
      <% @history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :cloths %>
    <%= f.fields_for :cloths_histories do |ff| %>
      <%= render 'cloths_fields', f: ff%>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Blink_server/app/views/histories/edit.html.erb
<h1>Editing History</h1>

<%= render 'form' %>

<%= link_to 'Show', @history %> |
<%= link_to 'Back', histories_path %>

Blink_server/app/views/histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Histories</h1>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @histories.each do |history| %>
      <tr>
        <td><%= history.location %></td>
        <td><%= history.user %></td>
        <td><%= link_to 'Show', history %></td>
        <td><%= link_to 'Edit', edit_history_path(history) %></td>
        <td><%= link_to 'Destroy', history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New History', new_history_path %>

Blink_server/app/views/histories/new.html.erb
<h1>New History</h1>

<%= render 'form' %>

<%= link_to 'Back', histories_path %>

Blink_server/app/views/histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @history.location %>
</p>

<p>
  <strong>User:</strong>
  <%= @history.user %>
</p>

<%= link_to 'Edit', edit_history_path(@history) %> |
<%= link_to 'Back', histories_path %>